#!/usr/bin/env bash
# Auto-generated by zetteldev.dask — supervises the scheduler for cluster 'default'.
while true; do
  /home/piriac/Wherewithal/25-WherewithLM/reason_reckon/.venv/bin/dask scheduler --host 127.0.0.1 --port 8786 \
    --dashboard-address :8787 --scheduler-file /home/piriac/Wherewithal/25-WherewithLM/reason_reckon/.zetteldev/dask/run/scheduler-default.json
  echo "[zdev-dask:default] scheduler exited; relaunch in 3s" >&2
  sleep 3
done
