#!/usr/bin/env bash
# Auto-generated by zetteldev.dask — supervises worker $1 for cluster 'default'.
idx="$1"
MODE="all"
GPUS=(0 1)
if [ "$MODE" = "pin" ]; then
  export CUDA_VISIBLE_DEVICES="${GPUS[$idx]}"
  RES="--resources GPU=1"
elif [ "$MODE" = "all" ]; then
  export CUDA_VISIBLE_DEVICES="0,1"
  RES=""
else
  export CUDA_VISIBLE_DEVICES=""
  RES=""
fi
# Keep JAX from swallowing the whole card on first use (lets workers coexist).
export XLA_PYTHON_CLIENT_PREALLOCATE=false
while true; do
  /home/piriac/Wherewithal/25-WherewithLM/reason_reckon/.venv/bin/dask worker --scheduler-file /home/piriac/Wherewithal/25-WherewithLM/reason_reckon/.zetteldev/dask/run/scheduler-default.json --name "w$idx" \
    --memory-limit auto \
    --lifetime 2h --lifetime-restart --lifetime-stagger 4m \
    $RES 
  echo "[zdev-dask:default] worker $idx exited; relaunch in 3s" >&2
  sleep 3
done
