# AUTOGENERATED! DO NOT EDIT! File to edit: ../experiments/02-diffusion-laziness/parameter-sensitivity-tests.ipynb.

# %% auto #0
__all__ = ['parameter_sensitivity_of_method']

# %% ../experiments/02-diffusion-laziness/parameter-sensitivity-tests.ipynb #93b4bc33-b960-4037-96ad-9ca1314a311c
def parameter_sensitivity_of_method(method, parameter_dict):
    # initialize the torus, saddle, and sphere datasets in a range of dimensions
    # run the given method on them, with form
    # output_list = method(X, params)
    # keep track of the results across parameter sets for each dataset
    # and return the variance per dataset and overall
    pass

# code here
