# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/repo_name',
                'doc_host': 'https://professorwug.github.io',
                'git_url': 'https://github.com/professorwug/repo_name',
                'lib_path': 'src'},
  'syms': {}}