name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: prefix-dev/setup-pixi@v0.6.0
        with:
          pixi-version: v0.19.1
          cache: true
          auth-host: prefix.dev
      - run: pixi run test
    [uses: fastai/workflows/nbdev-ci@master]
      
