name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - run: ls
      - uses: prefix-dev/setup-pixi@v0.6.0 # install pixi to set up package
        with:
          pixi-version: v0.19.1
          manifest-path: pyproject.toml
          cache: false
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
      - run: pixi run test_import # test that package can be imported
      - uses: fastai/workflows/nbdev-ci@master # nbdev tests: notebooks cleaned, tests run.
        with:
          python-version: 3.11
          pre: false
          skip_test: false
          flags: ""
          torch_cpu: true

      
